client:
  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      etcdClusters:
        - zone: embedded
          endpoints:
            - 127.0.0.1:2379
  writeConsistencyLevel: majority
  readConsistencyLevel: unstrict_majority
