# my global config
global:
  external_labels:
    role: "remote"
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'coordinator'
    static_configs:
      - targets: ['host.docker.internal:7203']

  - job_name: 'dbnode'
    static_configs:
      - targets: ['host.docker.internal:9004']

remote_read:
  - url: http://host.docker.internal:7201/api/v1/prom/remote/read

remote_write:
  - url: http://host.docker.internal:7201/api/v1/prom/remote/write
    write_relabel_configs:
      - target_label: metrics_storage
        replacement: m3db_remote
