listenAddress:
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

clusters:
## Fill-out the following and un-comment before using, and
## make sure indent by two spaces is applied.
#   - namespaces:
#       - namespace: default
#         retention: 48h
#         type: unaggregated
#     client:
#       config:
#         service:
#           env: default_env
#           zone: embedded
#           service: m3db
#           cacheDir: /var/lib/m3kv
#           etcdClusters:
#             - zone: embedded
#               endpoints:
#                 - M3DB_NODE_01_STATIC_IP_ADDRESS:2379
#                 - M3DB_NODE_02_STATIC_IP_ADDRESS:2379
#                 - M3DB_NODE_03_STATIC_IP_ADDRESS:2379
##                ... etc, list only M3DB seed nodes
#       writeConsistencyLevel: majority
#       readConsistencyLevel: unstrict_majority
