# m3query configuration for local development setup. Mostly the same as m3query-local-etcd.yml, but using fewer
# resources (threads primarily).
clusters:
  - namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - 127.0.0.1:2379

readWorkerPoolPolicy:
  grow: false
  size: 10

writeWorkerPoolPolicy:
  grow: false
  size: 10
