listenAddress:
  type: "config"
  value: "0.0.0.0:7201"

backend: grpc

rpc:
  remotes:
    - name: "remote"
      remoteListenAddresses: ["localhost:9000"]

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted
