logging:
    level: info
    stdout: true

http:
  host: 0.0.0.0
  port: 9000
  readTimeout: 10s
  writeTimeout: 10s

metrics:
  m3:
    hostPort: 127.0.0.1:5000  # local collector host port for m3 metrics
    service: r2ctl
    env: test
    includeHost: true
  samplingRate: 0.01

store:
  stub: true

