# Copyright (c) 2017 Uber Technologies, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

metrics:
  m3:
    hostPort: 127.0.0.1:5000  # local collector host port for m3 metrics
    service: m3aggregator
    env: test
    includeHost: true
  samplingRate: 0.01

msgpack:
  listenAddress: 0.0.0.0:6000
  retry:
    initialBackoff: 5ms
    backoffFactor: 2.0
    maxBackoff: 1s
    forever: true
    jitter: true
  iterator:
    ignoreHigherVersion: false
    readerBufferSize: 1440
    largeFloatsSize: 1024
    largeFloatsPool:
      buckets:
        - count: 1024
          capacity: 2048
        - count: 512
          capacity: 4096
        - count: 256
          capacity: 8192
        - count: 128
          capacity: 16384
        - count: 64
          capacity: 32768
        - count: 32
          capacity: 65536
    iteratorPool:
      size: 4096

http:
  listenAddress: 0.0.0.0:6001
  readTimeout: 45s
  writeTimeout: 45s

aggregator:
  stream:
    eps: 0.001
    capacity: 32
    streamPool:
      size: 4096
    samplePool:
      size: 4096
    floatsPool:
      buckets:
        - count: 4096
          capacity: 16
        - count: 2048
          capacity: 32
        - count: 1024
          capacity: 64
  timerQuantiles:
    - 0.5
    - 0.95
    - 0.99
  placementWatcher:
    namespace: /m3aggregator
    key: placement
  shardFnType: murmur32
  flushManager:
    checkEvery: 1s
    jitterEnabled: true
    numWorkersPerCPU: 0.125
  minFlushInterval: 5s
  maxFlushSize: 1440
  flush:
    type: logging
  entryTTL: 6h
  entryCheckInterval: 10m
  defaultPolicies:
    - 10s:2d
    - 1m:40d
  aggregationTypesPool:
    size: 1024
  counterElemPool:
    size: 4096
  timerElemPool:
    size: 4096
  gaugeElemPool:
    size: 4096
  entryPool:
    size: 4096
  bufferedEncoderPool:
    size: 4096
  quantilesPool:
    buckets:
      - count: 256
        capacity: 4
      - count: 128
        capacity: 8
