coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default: on
      x:
        flags: x
      cluster:
        flags: cluster
      msg:
        flags: msg
      metrics:
        flags: metrics
      aggregator:
        flags: aggregator
      collector:
        flags: collector
      query:
        flags: query
      dbnode:
        flags: dbnode
      m3ninx:
        flags: m3ninx
      m3nsch:
        flags: m3nsch
      m3em:
        flags: m3em
    patch:
      default: on
    changes:
      default: off

  flags:
    collector:
      paths:
        - src/collector/
        - src/cmd/services/m3collector/
    aggregator:
      paths:
        - src/aggregator/
        - src/cmd/services/m3aggregator
    query:
      paths:
        - src/query/
        - src/cmd/services/m3query/
    dbnode:
      paths:
        - src/dbnode/
        - src/cmd/services/m3dbnode/
    m3ninx:
      paths:
        - src/m3ninx/
    m3nsch:
      paths:
        - src/m3nsch/
        - src/cmd/services/m3nsch_server
        - src/cmd/services/m3nsch_client
    m3em:
      paths:
        - src/m3em/
        - src/cmd/services/m3em_agent
    x:
      paths:
        - src/x/
    cluster:
      paths:
        - src/cluster/
    msg:
      paths:
        - src/msg/
    metrics:
      paths:
        - src/metrics/

comment:
  layout: "header, reach, diff, flags, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
