coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
      coordinator:
        flags: coordinator
      dbnode:
        flags: dbnode
      m3ninx:
        flags: m3ninx
    patch:
      default: on
    changes:
      default: off

  flags:
    coordinator:
      paths:
        - src/coordinator/
        - src/cmd/services/m3coordinator/
    dbnode:
      paths:
        - src/dbnode/
        - src/cmd/services/m3dbnode/
    m3ninx:
      paths:
        - src/m3ninx/

comment:
  layout: "header, reach, diff, flags, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
