coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: off
      unittests:
        flags: unittests
      integration:
        flags: integration
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
