coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
      coordinator:
        flags: coordinator
      dbnode:
        flags: dbnode
      cmd:
        flags: cmd
    patch:
      default: on
    changes:
      default: off

  flags:
    coordinator:
      paths:
        - src/coordinator/
    dbnode:
      paths:
        - src/dbnode/
    cmd:
      paths:
        - src/cmd/

comment:
  layout: "header, reach, diff, flags, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
