rules:
  default:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts:
          - deploy/netlify
          - semaphoreci
          - license/cla
          - codecov/patch
          - codecov/project
    enabling_label: ready-to-be-merged

