# NB: need the following to ensure we pull down mockgen despite not calling the code
# directly in the repo. mockgen (the tool) requires the source to be present or its :(
required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/RoaringBitmap/roaring"
  version = "^0.4.0"

[[constraint]]
  name = "github.com/apache/thrift"
  source = "https://github.com/m3db/thrift"
  version = "0.9.3-pool-read-binary-2"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.10"

[[constraint]]
  name = "github.com/coreos/pkg"
  version = "4.0.0"

[[constraint]]
  name = "github.com/couchbase/vellum"
  source = "https://github.com/m3db/vellum"
  revision = "51c732079c882f52f8e6af889d99ac2a1611d5e4"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.4.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "^0.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/m3db/bitset"
  version = "2.0.0"

[[constraint]]
  name = "github.com/m3db/bloom"
  version = "3.0.0"

[[constraint]]
  name = "github.com/m3db/stackadler32"
  revision = "bfebcd73ef6ffe0ee30489227f0330c39064b674"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "^1.1"

[[constraint]]
  name = "github.com/pilosa/pilosa"
  version = "0.10.1"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "^1.2.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/uber-go/atomic"
  version = "^1.3.2"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = "^3.3.6"

[[constraint]]
  name = "golang.org/x/net"
  source = "https://github.com/golang/net"
  revision = "ab5485076ff3407ad2d02db054635913f017b0ed"

[[constraint]]
  name = "golang.org/x/sync"
  source = "https://github.com/golang/sync"
  revision = "1d60e4601c6fd243af51cc01ddf169918a5407ca"

[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go"
  version = "~1.7.3"

[[constraint]]
  name = "gopkg.in/validator.v2"
  source = "https://github.com/go-validator/validator.git"
  revision = "3e4f037f12a1221a0864cf0dd2e81c452ab22448"

[[constraint]]
  name = "gopkg.in/vmihailenco/msgpack.v2"
  source = "https://github.com/vmihailenco/msgpack.git"
  revision = "a1382b1ce0c749733b814157c245e02cc1f41076"

# test resources
[[constraint]]
  name = "github.com/golang/mock"
  version = "^1"

[[constraint]]
  name = "github.com/fortytw2/leaktest"
  revision = "b433bbd6d743c1854040b39062a3916ed5f78fe8"

[[constraint]]
  name = "github.com/leanovate/gopter"
  revision = "f0356731348c8fffa27bab27c37ec8be5b0662c8"

[prune]
  go-tests = true
  unused-packages = true
