logging:
  level: info

metrics:
  m3:
      hostPort: 127.0.0.1:9052
      service: m3dbnode
      env: production
      includeHost: true
  samplingRate: 0.01
#   runtime: simple

listenAddress: 0.0.0.0:9000
clusterListenAddress: 0.0.0.0:9001
httpNodeListenAddress: 0.0.0.0:9002
httpClusterListenAddress: 0.0.0.0:9003
debugListenAddress: 0.0.0.0:9004

hostID:
  resolver: config
  value: m3db_server_1

client:
  writeConsistencyLevel: majority
  readConsistencyLevel: unstrict_majority
#   clusterConnectConsistencyLevel: any

gcPercentage: 100

writeNewSeriesAsync: true
writeNewSeriesLimitPerSecond: 1048576
writeNewSeriesBackoffDuration: 2ms

bootstrap:
  bootstrappers:
      - filesystem
      - commitlog
      - peers
      - uninitialized_topology
  fs:
      numProcessorsPerCPU: 0.125

commitlog:
  flushMaxBytes: 524288
  flushEvery: 1s
  queue:
      calculationType: fixed
      size: 2097152

fs:
  filePathPrefix: /var/lib/m3db1

config:
  static:
      topology:
          shards: 64
          replicas: 1
          hosts:
            - hostID: m3db_server_1
              listenAddress: "0.0.0.0:9000"
      namespaces:
          - id: metrics
            retention:
              retentionPeriod: 24h
              blockSize: 4h
              bufferPast: 2h
            index:
              enabled: true
              blockSize: 4h
