---
apiVersion: v1
kind: ConfigMap
metadata:
  name: m3nsch-server-config
data:
  m3nsch_server.yaml: |+
    server:
      listenAddress: 0.0.0.0:2580
      debugAddress: 0.0.0.0:12580
      cpuFactor: 0.9

    metrics:
      prometheus:
        handlerPath: /metrics
      samplingRate: 1.0
      extended: detailed
      sanitization: prometheus

    m3nsch:
      concurrency: 2000
      numPointsPerDatum: 60

    dbClient:
      config:
        service:
          zone: default_zone
          env: default_env
          service: m3db
          etcdClusters:
            - zone: default_zone
              endpoints:
                - etcd-0.etcd:2379
                - etcd-1.etcd:2379
                - etcd-2.etcd:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority
      writeTimeout: 10s
      fetchTimeout: 15s
      connectTimeout: 20s
      writeRetry:
          initialBackoff: 500ms
          backoffFactor: 3
          maxRetries: 2
          jitter: true
      fetchRetry:
          initialBackoff: 500ms
          backoffFactor: 2
          maxRetries: 3
          jitter: true
      backgroundHealthCheckFailLimit: 4
      backgroundHealthCheckFailThrottleFactor: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: m3nsch-agent
  labels:
    app: m3nsch
    component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: agent
    port: 2580
  - name: debug
    port: 12580
  selector:
    app: m3nsch
    component: agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3nsch-agent
  labels:
    app: m3nsch
    component: agent
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: m3nsch
      component: agent
  template:
    metadata:
      labels:
        app: m3nsch
        component: agent
    spec:
      containers:
      - name: m3nsch-agent
        image: quay.io/m3/m3nsch:latest
        args:
        - "-f"
        - "/etc/m3nsch/m3nsch_server.yaml"
        volumeMounts:
        - name: server-config
          mountPath: /etc/m3nsch/
        imagePullPolicy: Always
        ports:
        - name: agent
          containerPort: 2580
          protocol: TCP
        - name: debug
          containerPort: 12580
          protocol: TCP
      volumes:
      - name: server-config
        configMap:
          name: m3nsch-server-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3nsch-client
  labels:
    app: m3nsch
    component: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m3nsch
      component: client
  template:
    metadata:
      labels:
        app: m3nsch
        component: client
    spec:
      containers:
      - name: m3nsch-client
        image: quay.io/m3/m3nsch:latest
        command:
        - "/bin/ash"
        args: ["-c", "while true; do sleep 300; done"]
        imagePullPolicy: Always
      # If you're running in a shell it may take a while to kill
      terminationGracePeriodSeconds: 5
