DirectoryPath: site/public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: true
IgnoreAltMissing: false
CheckImages: false
CheckScripts: false
CheckMeta: false
CheckMetaRefresh: false
CheckLinks: false
EnforceHTML5: false
EnforceHTTPS: false
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
TestFilesConcurrently: false
DocumentConcurrencyLimit: 1
HTTPConcurrencyLimit: 1
IgnoreURLs:
- "youtu.be"
- "youtube.com"
- "cassandra.apache.org"
- "slideshare.net"
- "meetup.com"
- "github.com/m3db/m3/tree/docs-test/site/content/docs"
- "github.com/m3db/m3/tree/master/site/content/docs"