steps:
  # We add a wait step here so that docker images and docs won't get built
  # unless rest of CI passes.
  # Currently only exists for operator docs
  - wait
  - name: "Docs build and push :books:"
    command: ".buildkite/scripts/docs_push.sh"
    agents:
      queue: "buildkite-gcp"
    timeout_in_minutes: 20
    # Don't let doc failures block other steps (like docker builds)
    soft_fail:
    - exit_status: "*"
    retry:
      automatic:
        limit: 1
      manual: true
    plugins:
      docker-compose#v2.5.1:
        run: docs
        config: .buildkite/docs-docker-compose.yml
        workdir: /go/src/github.com/m3db/m3
