common: &common
  timeout_in_minutes: 20
  agents:
    queue: workers
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Integration (:docker:)"
    command: make clean install-vendor-m3 docker-integration-test
    parallelism: 1
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.13.x
    plugins:
        gopath-checkout#v1.0.1:
          import: github.com/m3db/m3
    <<: *common
