container:
  kubernetes: &kubernetes
    gitEnvFrom:
      - secretRef:
          name: oss-github-ssh-credentials
    sidecars:
      - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
        volumeMounts:
          - mountPath: /var/run/
            name: docker-sock
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
    mirrorVolumeMounts: true # CRITICAL: this must be at the same indentation level as sidecars
    podSpec: &podSpec
      containers:
        - &commandContainer
          image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
          command:
            - |-
              echo "Command step was not overridden."
              exit 1
          volumeMounts:
            - mountPath: /var/run/
              name: docker-sock
          resources:
            requests:
              cpu: 7500m
              memory: 28G
      volumes:
        - name: docker-sock
          emptyDir: {}

agents:
  queue: "buildkite-gcp"

common: &common
  timeout_in_minutes: 20
  agents:
    queue: "buildkite-gcp"
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

# Temporarily disable codecov while we investigate issues with uploading.
env:
  SKIP_CODECOV: "true"

steps:
  - name: "Unit %n"
    parallelism: 4
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-base
