container:
  kubernetes: &kubernetes
    gitEnvFrom:
      - secretRef:
          name: oss-github-ssh-credentials
    sidecars:
      - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
        volumeMounts:
          - mountPath: /var/run/
            name: docker-sock
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
    mirrorVolumeMounts: true # CRITICAL: this must be at the same indentation level as sidecars
    podSpec: &podSpec
      containers:
        - &commandContainer
          image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
          command:
            - |-
              echo "Command step was not overridden."
              exit 1
          volumeMounts:
            - mountPath: /var/run/
              name: docker-sock
          resources:
            requests:
              cpu: 7500m
              memory: 28G
      volumes:
        - name: docker-sock
          emptyDir: {}

agents:
  queue: "buildkite-gcp"

common: &common
  timeout_in_minutes: 20
  agents:
    queue: "buildkite-gcp"
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

# Temporarily disable codecov while we investigate issues with uploading.
env:
  SKIP_CODECOV: "true"

# Buildkite pipeline is currently broken, and we are working on fixing it. In the meantime, we are temporarily
# disabling steps until it is fixed. ISSUE: https://github.com/m3db/m3/issues/4274
steps:
#  - name: "Codegen"
#    env:
#      CGO_ENABLED: 0
#      GIMME_GO_VERSION: 1.18.x
#    plugins:
#      gopath-checkout#v1.0.1:
#        import: github.com/m3db/m3
#      docker#v3.0.1:
#        image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
#        volumes:
#          - .:/go/src/github.com/m3db/m3
#          - /var/run/docker.sock:/var/run/docker.sock
#      kubernetes:
#        <<: *kubernetes
#        podSpec:
#          <<: *podSpec
#          containers:
#            - <<: *commandContainer
#              command:
#                - |-
#                  make clean install-vendor-m3 test-all-gen
#    <<: *common
  - name: "Unit %n"
    parallelism: 4
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-base
    <<: *common
  - name: "Big Unit %n"
    parallelism: 2
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-big-base
    <<: *common
  - name: "Services, Tools"
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 services tools
    <<: *common
  - name: "Lint"
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.18.x
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean lint
    <<: *common
  - label: "Integration (:docker:)"
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.18.x
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 docker-integration-test
    <<: *common
  - label: "M3 Cluster Integration Tests"
    env:
      CGO_ENABLED: 0
      GIMME_GO_VERSION: 1.18.x
    plugins:
      gopath-checkout#v1.0.1:
        import: github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean test-ci-cluster-integration
    <<: *common
  - label: "M3 Cluster Integration Test Harness Tests"
    skip: "NB(nate): temporarily disabling to resolve some tests flakes"
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean test-ci-test-harness
    <<: *common
#  - name: "Prometheus compatibility (:docker:)"
#    command: make clean install-vendor-m3 docker-compatibility-test
#    parallelism: 1
#    env:
#      CGO_ENABLED: 0
#      GIMME_GO_VERSION: 1.18.x
#    plugins:
#        gopath-checkout#v1.0.1:
#          import: github.com/m3db/m3
#    <<: *common
  - name: "Integration (dbnode Recently Read) %n"
    parallelism: 2
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-ci-integration-dbnode cache_policy=recently_read
    <<: *common
  - name: "Integration (dbnode LRU) %n"
    parallelism: 2
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-ci-integration-dbnode cache_policy=lru
    <<: *common
  - name: "Integration (aggregator TCP client) %n"
    parallelism: 1
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-ci-integration-aggregator aggregator_client=tcp
    <<: *common
  - name: "Integration (aggregator m3msg client) %n"
    parallelism: 1
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-ci-integration-aggregator aggregator_client=m3msg
    <<: *common
  - label: "Integration (m3em, cluster, msg, metrics) %n"
    parallelism: 4
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  make clean install-vendor-m3 test-ci-integration-m3em test-ci-integration-cluster test-ci-integration-msg test-ci-integration-metrics
    <<: *common
# Commenting out Documentation test for now because of issue with access tokens. Also a low priority test, as it checks
# for broken links in the documentation.
#  - name: "Documentation tests"
#    command: make clean install-vendor-m3 docs-test
#    env:
#      CGO_ENABLED: 0
#      GIMME_GO_VERSION: 1.18.x
#    plugins:
#        gopath-checkout#v1.0.1:
#          import: github.com/m3db/m3
#    <<: *common
#  - label: "FOSSA license scan"
#    command: make clean install-vendor-m3 fossa
#    plugins:
#      docker-compose#v2.5.1:
#        run: app
#        workdir: /go/src/github.com/m3db/m3
#        env:
#          - FOSSA_API_KEY
#    <<: *common
  - name: "Check for docker and docs builds :docker: :books:"
    plugins:
      kubernetes:
        <<: *kubernetes
        podSpec:
          <<: *podSpec
          containers:
            - <<: *commandContainer
              command:
                - |-
                  .buildkite/scripts/check_do_docs.sh
                  .ci/docker/check_do_docker.sh
    <<: *common
