listenAddress: 0.0.0.0:7201

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:3030
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

tagOptions:
  idScheme: quoted

clusterManagement:
  etcd:
    env: default_env
    zone: embedded
    service: m3db
    cacheDir: /var/lib/m3kv
    etcdClusters:
      - zone: embedded
        endpoints:
          - 127.0.0.1:2379

backend: prom-remote

prometheusRemoteBackend:
  endpoints:
    - name: unaggregated
      address: "http://host.docker.internal:9090/api/v1/write"
    - name: aggregated
      address: "http://host.docker.internal:9090/api/v1/write"
      storagePolicy:
        retention: 1440h
        resolution: 1m
        downsample:
          all: false

downsample:
  matcher:
    requireNamespaceWatchOnInit: false
  rules:
    mappingRules:
      - name: "drop metric from unaggregated endpoint"
        filter: "__name__:coordinator_ingest_latency_count"
        drop: True
      - name: "metric @ different resolution"
        filter: "__name__:coordinator_ingest_latency_count"
        aggregations: ["Last"]
        storagePolicies:
          - retention: 1440h
            resolution: 1m