listenAddress: 0.0.0.0:7201

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:3030
  sanitization: prometheus
  samplingRate: 1.0

backend: prom-remote

prometheusRemoteBackend:
  endpoints:
    - name: unaggregated
      address: "http://host.docker.internal:9090/api/v1/write"
    - name: aggregated
      address: "http://host.docker.internal:9090/api/v1/write"
      storagePolicy:
        retention: 1440h
        resolution: 5m
        downsample:
          all: false

downsample:
  matcher:
    requireNamespaceWatchOnInit: false
  rules:
    mappingRules:
      - name: "drop metric from unaggregated endpoint"
        filter: "__name__:coordinator_ingest_latency_count"
        drop: True
      - name: "metric @ different resolution"
        filter: "__name__:coordinator_ingest_latency_count"
        aggregations: ["Last"]
        storagePolicies:
          - retention: 1440h
            resolution: 5m
