language: go
go:
  - "1.9.x"
  - "1.10.x"
install: make install-ci
env:
  global:
    - TEST_TIMEOUT_SCALE=20 # Set higher timeouts for Travis
    - PACKAGE=github.com/$TRAVIS_REPO_SLUG
script:
 - make all
