language: go
go:
  - 1.6
  - 1.7
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide
  - git checkout v0.12.3
  - go install
  - cd $GOPATH/src/github.com/m3db/m3cluster
  - glide install
env:
 # Set higher timeouts for Travis
 - TEST_TIMEOUT_SCALE=20
 - PACKAGE=github.com/m3db/m3cluster
script:
 - make lint
 - make test-ci-unit
