FROM alpine:3.7

COPY bin/m3dbnode /bin/m3dbnode
RUN mkdir -p /etc/m3/
COPY src/cmd/services/m3dbnode/config/m3dbnode.yml /etc/m3/m3dbnode.yml

EXPOSE 9000/tcp
EXPOSE 9001/tcp
EXPOSE 9002/tcp
EXPOSE 9003/tcp
EXPOSE 9004/tcp

ENTRYPOINT ["/bin/m3dbnode", "-f", "/etc/m3/m3dbnode.yml"]
