FROM golang:1.10-alpine

# Install Glide
RUN apk add --update glide git make bash

# Add source code
RUN mkdir -p ${GOPATH}/src/github.com/m3db/m3db 
ADD . ${GOPATH}/src/github.com/m3db/m3db

# Build m3dbnode binary 
RUN cd ${GOPATH}/src/github.com/m3db/m3db/ && \
    git submodule update --init && \
    glide install && \
    make m3dbnode-linux-amd64

ENTRYPOINT ["/go/src/github.com/m3db/m3db/bin/m3dbnode", \
            "-f", \
            "/go/src/github.com/m3db/m3db/src/cmd/services/m3dbnode/config/m3dbnode.yml"]
