language: go
go:
  - "1.9.x"
  - "1.10.x"
install: make install-ci
env:
 # Set higher timeouts and package name for travis
 - TEST_TIMEOUT_SCALE=20 PACKAGE=github.com/m3db/m3ctl
sudo: required
dist: trusty
script:
 - make all
