// Copyright (c) 2018 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m3db/m3aggregator/tools/deploy/planner.go

package deploy

import (
	"reflect"

	"github.com/golang/mock/gomock"
)

// Mockplanner is a mock of planner interface
type Mockplanner struct {
	ctrl     *gomock.Controller
	recorder *MockplannerMockRecorder
}

// MockplannerMockRecorder is the mock recorder for Mockplanner
type MockplannerMockRecorder struct {
	mock *Mockplanner
}

// NewMockplanner creates a new mock instance
func NewMockplanner(ctrl *gomock.Controller) *Mockplanner {
	mock := &Mockplanner{ctrl: ctrl}
	mock.recorder = &MockplannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *Mockplanner) EXPECT() *MockplannerMockRecorder {
	return _m.recorder
}

// GeneratePlan mocks base method
func (_m *Mockplanner) GeneratePlan(toDeploy instanceMetadatas, all instanceMetadatas) (deploymentPlan, error) {
	ret := _m.ctrl.Call(_m, "GeneratePlan", toDeploy, all)
	ret0, _ := ret[0].(deploymentPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePlan indicates an expected call of GeneratePlan
func (_mr *MockplannerMockRecorder) GeneratePlan(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GeneratePlan", reflect.TypeOf((*Mockplanner)(nil).GeneratePlan), arg0, arg1)
}

// GenerateOneStep mocks base method
func (_m *Mockplanner) GenerateOneStep(toDeploy instanceMetadatas, all instanceMetadatas) (deploymentStep, error) {
	ret := _m.ctrl.Call(_m, "GenerateOneStep", toDeploy, all)
	ret0, _ := ret[0].(deploymentStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateOneStep indicates an expected call of GenerateOneStep
func (_mr *MockplannerMockRecorder) GenerateOneStep(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GenerateOneStep", reflect.TypeOf((*Mockplanner)(nil).GenerateOneStep), arg0, arg1)
}
