logging:
  level: info

metrics:
    prometheus:
        handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

listenAddress: 0.0.0.0:9000
clusterListenAddress: 0.0.0.0:9001
httpNodeListenAddress: 0.0.0.0:9002
httpClusterListenAddress: 0.0.0.0:9003
debugListenAddress: 0.0.0.0:9004

hostID:
  resolver: config
  value: m3db_server_2

client:
  writeConsistencyLevel: majority
  readConsistencyLevel: unstrict_majority
  clusterConnectConsistencyLevel: any
  writeTimeout: 10s
  fetchTimeout: 15s
  connectTimeout: 20s
  writeRetry:
      initialBackoff: 500ms
      backoffFactor: 3
      maxRetries: 2
      jitter: true
  fetchRetry:
      initialBackoff: 500ms
      backoffFactor: 2
      maxRetries: 3
      jitter: true
  backgroundHealthCheckFailLimit: 4
  backgroundHealthCheckFailThrottleFactor: 0.5

gcPercentage: 100

writeNewSeriesAsync: true
writeNewSeriesLimitPerSecond: 1048576
writeNewSeriesBackoffDuration: 2ms

bootstrap:
  bootstrappers:
      - filesystem
      - commitlog
      - peers
      - uninitialized_topology
  fs:
      numProcessorsPerCPU: 0.125

commitlog:
  flushMaxBytes: 524288
  flushEvery: 1s
  queue:
      calculationType: fixed
      size: 2097152
  blockSize: 10m

fs:
  filePathPrefix: /var/lib/m3db

config:
  static:
      topology:
          shards: 64
          hosts:
            - host: m3db_server_1
              listenAddress: "0.0.0.0:9000"
            - host: m3db_server_2
              listenAddress: "0.0.0.0:9000"
            - host: m3db_server_3
              listenAddress: "0.0.0.0:9000"
      namespaces:
          - name: metrics
            options:
            retention:
              retentionPeriod: 24h
              blockSize: 4h
              bufferPast: 2h
