client:
  config:
    static:
      # listenAddress: 0.0.0.0:9000
      topology:
          shards: 64
          hosts:
            - host: m3db_server_1
              listenAddress: "0.0.0.0:9000"
            - host: m3db_server_2
              listenAddress: "0.0.0.0:9000"
            - host: m3db_server_3
              listenAddress: "0.0.0.0:9000"
      namespaces:
          - name: metrics
            options:
            retention:
              retentionPeriod: 24h
              blockSize: 1h
          - name: other_metrics
            retention:
              retentionPeriod: 24h
              blockSize: 1h
            options:
  writeConsistencyLevel: majority
  readConsistencyLevel: unstrict_majority
  clusterConnectConsistencyLevel: any
  writeTimeout: 10s
  fetchTimeout: 15s
  connectTimeout: 20s
  writeRetry:
      initialBackoff: 500ms
      backoffFactor: 3
      maxRetries: 2
      jitter: true
  fetchRetry:
      initialBackoff: 500ms
      backoffFactor: 2
      maxRetries: 3
      jitter: true
  backgroundHealthCheckFailLimit: 4
  backgroundHealthCheckFailThrottleFactor: 0.5
