logging:
    level: info
    # file: /var/log/m3dbnode.log

metrics:
    prometheus:
        handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

listenAddress: 0.0.0.0:9000
clusterListenAddress: 0.0.0.0:9001
httpNodeListenAddress: 0.0.0.0:9002
httpClusterListenAddress: 0.0.0.0:9003
debugListenAddress: 0.0.0.0:9004

hostID:
    resolver: hostname
    # value: {{.HostID}}

client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

gcPercentage: 100

writeNewSeriesAsync: true
writeNewSeriesLimitPerSecond: 1048576
writeNewSeriesBackoffDuration: 2ms

bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    fs:
        numProcessorsPerCPU: 0.125

commitlog:
    flushMaxBytes: 524288
    flushEvery: 1s
    queue:
        calculationType: fixed
        size: 2097152

fs:
    filePathPrefix: /var/lib/m3db

config:
    static:
        topology:
            shards: 64
            hosts:
              - hostID: <host_id>
                listenAddress: "0.0.0.0:9000"
        namespaces:
            - name: metrics
              options:
              retention:
                retentionPeriod: 24h
                blockSize: 4h
                bufferPast: 2h
