// Copyright (c) 2018 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/m3db/m3db/persist/fs (interfaces: FileSetWriter,FileSetReader,FileSetSeeker)

// Package fs is a generated GoMock package.
package fs

import (
	"reflect"
	"time"

	"github.com/m3db/m3x/checked"
	"github.com/m3db/m3x/ident"
	time0 "github.com/m3db/m3x/time"

	"github.com/golang/mock/gomock"
)

// MockFileSetWriter is a mock of FileSetWriter interface
type MockFileSetWriter struct {
	ctrl     *gomock.Controller
	recorder *MockFileSetWriterMockRecorder
}

// MockFileSetWriterMockRecorder is the mock recorder for MockFileSetWriter
type MockFileSetWriterMockRecorder struct {
	mock *MockFileSetWriter
}

// NewMockFileSetWriter creates a new mock instance
func NewMockFileSetWriter(ctrl *gomock.Controller) *MockFileSetWriter {
	mock := &MockFileSetWriter{ctrl: ctrl}
	mock.recorder = &MockFileSetWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileSetWriter) EXPECT() *MockFileSetWriterMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockFileSetWriter) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockFileSetWriterMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileSetWriter)(nil).Close))
}

// Open mocks base method
func (m *MockFileSetWriter) Open(arg0 WriterOpenOptions) error {
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open
func (mr *MockFileSetWriterMockRecorder) Open(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFileSetWriter)(nil).Open), arg0)
}

// Write mocks base method
func (m *MockFileSetWriter) Write(arg0 ident.ID, arg1 checked.Bytes, arg2 uint32) error {
	ret := m.ctrl.Call(m, "Write", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockFileSetWriterMockRecorder) Write(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFileSetWriter)(nil).Write), arg0, arg1, arg2)
}

// WriteAll mocks base method
func (m *MockFileSetWriter) WriteAll(arg0 ident.ID, arg1 []checked.Bytes, arg2 uint32) error {
	ret := m.ctrl.Call(m, "WriteAll", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAll indicates an expected call of WriteAll
func (mr *MockFileSetWriterMockRecorder) WriteAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAll", reflect.TypeOf((*MockFileSetWriter)(nil).WriteAll), arg0, arg1, arg2)
}

// MockFileSetReader is a mock of FileSetReader interface
type MockFileSetReader struct {
	ctrl     *gomock.Controller
	recorder *MockFileSetReaderMockRecorder
}

// MockFileSetReaderMockRecorder is the mock recorder for MockFileSetReader
type MockFileSetReaderMockRecorder struct {
	mock *MockFileSetReader
}

// NewMockFileSetReader creates a new mock instance
func NewMockFileSetReader(ctrl *gomock.Controller) *MockFileSetReader {
	mock := &MockFileSetReader{ctrl: ctrl}
	mock.recorder = &MockFileSetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileSetReader) EXPECT() *MockFileSetReaderMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockFileSetReader) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockFileSetReaderMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileSetReader)(nil).Close))
}

// Entries mocks base method
func (m *MockFileSetReader) Entries() int {
	ret := m.ctrl.Call(m, "Entries")
	ret0, _ := ret[0].(int)
	return ret0
}

// Entries indicates an expected call of Entries
func (mr *MockFileSetReaderMockRecorder) Entries() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockFileSetReader)(nil).Entries))
}

// EntriesRead mocks base method
func (m *MockFileSetReader) EntriesRead() int {
	ret := m.ctrl.Call(m, "EntriesRead")
	ret0, _ := ret[0].(int)
	return ret0
}

// EntriesRead indicates an expected call of EntriesRead
func (mr *MockFileSetReaderMockRecorder) EntriesRead() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntriesRead", reflect.TypeOf((*MockFileSetReader)(nil).EntriesRead))
}

// MetadataRead mocks base method
func (m *MockFileSetReader) MetadataRead() int {
	ret := m.ctrl.Call(m, "MetadataRead")
	ret0, _ := ret[0].(int)
	return ret0
}

// MetadataRead indicates an expected call of MetadataRead
func (mr *MockFileSetReaderMockRecorder) MetadataRead() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetadataRead", reflect.TypeOf((*MockFileSetReader)(nil).MetadataRead))
}

// Open mocks base method
func (m *MockFileSetReader) Open(arg0 ReaderOpenOptions) error {
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open
func (mr *MockFileSetReaderMockRecorder) Open(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFileSetReader)(nil).Open), arg0)
}

// Range mocks base method
func (m *MockFileSetReader) Range() time0.Range {
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(time0.Range)
	return ret0
}

// Range indicates an expected call of Range
func (mr *MockFileSetReaderMockRecorder) Range() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockFileSetReader)(nil).Range))
}

// Read mocks base method
func (m *MockFileSetReader) Read() (ident.ID, checked.Bytes, uint32, error) {
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(ident.ID)
	ret1, _ := ret[1].(checked.Bytes)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Read indicates an expected call of Read
func (mr *MockFileSetReaderMockRecorder) Read() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFileSetReader)(nil).Read))
}

// ReadBloomFilter mocks base method
func (m *MockFileSetReader) ReadBloomFilter() (*ManagedConcurrentBloomFilter, error) {
	ret := m.ctrl.Call(m, "ReadBloomFilter")
	ret0, _ := ret[0].(*ManagedConcurrentBloomFilter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBloomFilter indicates an expected call of ReadBloomFilter
func (mr *MockFileSetReaderMockRecorder) ReadBloomFilter() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBloomFilter", reflect.TypeOf((*MockFileSetReader)(nil).ReadBloomFilter))
}

// ReadMetadata mocks base method
func (m *MockFileSetReader) ReadMetadata() (ident.ID, int, uint32, error) {
	ret := m.ctrl.Call(m, "ReadMetadata")
	ret0, _ := ret[0].(ident.ID)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(uint32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ReadMetadata indicates an expected call of ReadMetadata
func (mr *MockFileSetReaderMockRecorder) ReadMetadata() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMetadata", reflect.TypeOf((*MockFileSetReader)(nil).ReadMetadata))
}

// Status mocks base method
func (m *MockFileSetReader) Status() FileSetReaderStatus {
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(FileSetReaderStatus)
	return ret0
}

// Status indicates an expected call of Status
func (mr *MockFileSetReaderMockRecorder) Status() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockFileSetReader)(nil).Status))
}

// Validate mocks base method
func (m *MockFileSetReader) Validate() error {
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate
func (mr *MockFileSetReaderMockRecorder) Validate() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockFileSetReader)(nil).Validate))
}

// ValidateData mocks base method
func (m *MockFileSetReader) ValidateData() error {
	ret := m.ctrl.Call(m, "ValidateData")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateData indicates an expected call of ValidateData
func (mr *MockFileSetReaderMockRecorder) ValidateData() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateData", reflect.TypeOf((*MockFileSetReader)(nil).ValidateData))
}

// ValidateMetadata mocks base method
func (m *MockFileSetReader) ValidateMetadata() error {
	ret := m.ctrl.Call(m, "ValidateMetadata")
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateMetadata indicates an expected call of ValidateMetadata
func (mr *MockFileSetReaderMockRecorder) ValidateMetadata() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateMetadata", reflect.TypeOf((*MockFileSetReader)(nil).ValidateMetadata))
}

// MockFileSetSeeker is a mock of FileSetSeeker interface
type MockFileSetSeeker struct {
	ctrl     *gomock.Controller
	recorder *MockFileSetSeekerMockRecorder
}

// MockFileSetSeekerMockRecorder is the mock recorder for MockFileSetSeeker
type MockFileSetSeekerMockRecorder struct {
	mock *MockFileSetSeeker
}

// NewMockFileSetSeeker creates a new mock instance
func NewMockFileSetSeeker(ctrl *gomock.Controller) *MockFileSetSeeker {
	mock := &MockFileSetSeeker{ctrl: ctrl}
	mock.recorder = &MockFileSetSeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileSetSeeker) EXPECT() *MockFileSetSeekerMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockFileSetSeeker) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockFileSetSeekerMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileSetSeeker)(nil).Close))
}

// ConcurrentClone mocks base method
func (m *MockFileSetSeeker) ConcurrentClone() (ConcurrentFileSetSeeker, error) {
	ret := m.ctrl.Call(m, "ConcurrentClone")
	ret0, _ := ret[0].(ConcurrentFileSetSeeker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConcurrentClone indicates an expected call of ConcurrentClone
func (mr *MockFileSetSeekerMockRecorder) ConcurrentClone() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcurrentClone", reflect.TypeOf((*MockFileSetSeeker)(nil).ConcurrentClone))
}

// ConcurrentIDBloomFilter mocks base method
func (m *MockFileSetSeeker) ConcurrentIDBloomFilter() *ManagedConcurrentBloomFilter {
	ret := m.ctrl.Call(m, "ConcurrentIDBloomFilter")
	ret0, _ := ret[0].(*ManagedConcurrentBloomFilter)
	return ret0
}

// ConcurrentIDBloomFilter indicates an expected call of ConcurrentIDBloomFilter
func (mr *MockFileSetSeekerMockRecorder) ConcurrentIDBloomFilter() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcurrentIDBloomFilter", reflect.TypeOf((*MockFileSetSeeker)(nil).ConcurrentIDBloomFilter))
}

// Entries mocks base method
func (m *MockFileSetSeeker) Entries() int {
	ret := m.ctrl.Call(m, "Entries")
	ret0, _ := ret[0].(int)
	return ret0
}

// Entries indicates an expected call of Entries
func (mr *MockFileSetSeekerMockRecorder) Entries() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Entries", reflect.TypeOf((*MockFileSetSeeker)(nil).Entries))
}

// Open mocks base method
func (m *MockFileSetSeeker) Open(arg0 ident.ID, arg1 uint32, arg2 time.Time) error {
	ret := m.ctrl.Call(m, "Open", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open
func (mr *MockFileSetSeekerMockRecorder) Open(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFileSetSeeker)(nil).Open), arg0, arg1, arg2)
}

// Range mocks base method
func (m *MockFileSetSeeker) Range() time0.Range {
	ret := m.ctrl.Call(m, "Range")
	ret0, _ := ret[0].(time0.Range)
	return ret0
}

// Range indicates an expected call of Range
func (mr *MockFileSetSeekerMockRecorder) Range() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockFileSetSeeker)(nil).Range))
}

// SeekByID mocks base method
func (m *MockFileSetSeeker) SeekByID(arg0 ident.ID) (checked.Bytes, error) {
	ret := m.ctrl.Call(m, "SeekByID", arg0)
	ret0, _ := ret[0].(checked.Bytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SeekByID indicates an expected call of SeekByID
func (mr *MockFileSetSeekerMockRecorder) SeekByID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekByID", reflect.TypeOf((*MockFileSetSeeker)(nil).SeekByID), arg0)
}

// SeekByIndexEntry mocks base method
func (m *MockFileSetSeeker) SeekByIndexEntry(arg0 IndexEntry) (checked.Bytes, error) {
	ret := m.ctrl.Call(m, "SeekByIndexEntry", arg0)
	ret0, _ := ret[0].(checked.Bytes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SeekByIndexEntry indicates an expected call of SeekByIndexEntry
func (mr *MockFileSetSeekerMockRecorder) SeekByIndexEntry(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekByIndexEntry", reflect.TypeOf((*MockFileSetSeeker)(nil).SeekByIndexEntry), arg0)
}

// SeekIndexEntry mocks base method
func (m *MockFileSetSeeker) SeekIndexEntry(arg0 ident.ID) (IndexEntry, error) {
	ret := m.ctrl.Call(m, "SeekIndexEntry", arg0)
	ret0, _ := ret[0].(IndexEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SeekIndexEntry indicates an expected call of SeekIndexEntry
func (mr *MockFileSetSeekerMockRecorder) SeekIndexEntry(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeekIndexEntry", reflect.TypeOf((*MockFileSetSeeker)(nil).SeekIndexEntry), arg0)
}
