app:
  image: golang:1.10.4-stretch
  volumes:
    - ../:/go/src/github.com/m3db/m3cluster
  environment:
    - CI
    - BUILDKITE
    - BUILDKITE_AGENT_ACCESS_TOKEN
    - BUILDKITE_JOB_ID
    - BUILDKITE_BUILD_ID
    - BUILDKITE_BUILD_NUMBER
    - BUILDKITE_BRANCH
    - BUILDKITE_BUILD_URL
    - BUILDKITE_PROJECT_SLUG
    - BUILDKITE_COMMIT
    - BUILDKITE_PULL_REQUEST
    - BUILDKITE_TAG
    - CODECOV_TOKEN
