version: "3.5"
services:
  etcd01:
    expose:
      - "2379-2380"
    ports:
      - "0.0.0.0:2379-2380:2379-2380"
    networks:
      - backend
    image: gcr.io/etcd-development/etcd:v3.5.15
    command:
      - "etcd"
      - "--name"
      - "etcd01"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--advertise-client-urls"
      - "http://etcd01:2379"
      - "--initial-cluster-token"
      - "etcd-cluster-1"
      - "--initial-advertise-peer-urls"
      - "http://etcd01:2380"
      - "--initial-cluster"
      - "etcd01=http://etcd01:2380"
      - "--initial-cluster-state"
      - "new"
      - "--data-dir"
      - "/var/lib/etcd"

  m3coordinator01:
    expose:
      - "7201"
    ports:
      - "0.0.0.0:7201:7201"
    networks:
      - backend
    build:
      context: ../../../bin
      dockerfile: ./docker/m3coordinator/development.Dockerfile
    image: m3coordinator:dev
    volumes:
      - "./m3coordinator.yml:/etc/m3coordinator/m3coordinator.yml"

  # M3 Aggregator nodes - these will be generated by the start script
  # based on M3_AGGREGATOR_NODE_COUNT environment variable

networks:
  backend:
