coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
      coordinator:
        flags: coordinator
      db:
        flags: db
    patch:
      default: on
    changes:
      default: off

  flags:
    coordinator:
      paths:
        - src/coordinator/
    db:
      paths:
        - client/
        - clock/
        - digest/
        - docs/
        - encoding/
        - environment/
        - example/
        - generated/
        - integration/
        - kvconfig/
        - network/
        - persist/
        - ratelimit/
        - retention/
        - runtime/
        - serialize/
        - services/
        - sharding/
        - storage/
        - tools/
        - topology/
        - ts/
        - x/

comment:
  layout: "header, reach, diff, flags, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
