# -*- mode: ruby -*-
# vi: set ft=ruby :

# Documentation:
# See vagrant/README.md

require 'etc'

# Boxes available at: https://vagrantcloud.com/search
$BOX=ENV['BOX']
$GOOGLE_PROJECT_ID = ENV['GOOGLE_PROJECT_ID']
$GOOGLE_JSON_KEY_LOCATION = ENV['GOOGLE_JSON_KEY_LOCATION']
$USER = ENV['USER']
$SSH_KEY = ENV['SSH_KEY']

Vagrant.configure("2") do |config|

  config.vm.define "primary", primary: true do |machine|
      machine.vm.box = $BOX
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.network "forwarded_port", guest: 3000, host: 3333

      # Local development provider
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "m3-dev-k8s"

        # Assign half CPU cores
        vb.cpus = Etc.nprocessors / 2

        # Assign 3072mb RAM (has been known to start paging using only 2gb RAM)
        vb.memory = 3072
      end

      machine.vm.provider :google do |google, override|
        # Normal benchmarks:
        google.machine_type = "n1-standard-16"
        google.preemptible = false

        # For heavy benchmarks, use pre-emptible n1-standard-64:
        # google.machine_type = "n1-standard-64"
        # google.preemptible = true
        # google.auto_restart = false
        # google.on_host_maintenance = "TERMINATE"

        google.google_project_id = $GOOGLE_PROJECT_ID
        google.google_json_key_location = $GOOGLE_JSON_KEY_LOCATION

        google.name = "m3-dev-primary-" + $USER
        google.image_family = "ubuntu-1604-lts"
        google.zone = "us-central1-f"
        google.metadata = {}
        google.tags = ['vagrantbox', 'dev', 'network-m3coordinator']
        google.disk_size = '50' # 50gb
        google.disk_type = 'pd-ssd'
        google.autodelete_disk = true

        override.ssh.username = $USER
        override.ssh.private_key_path = $SSH_KEY
      end

      machine.vm.provision "file", source: "../provision", destination: "$HOME/provision"
      machine.vm.provision "file", source: "../../../kube", destination: "$HOME/provision/kube"

      machine.vm.provision "shell", privileged: true, inline: <<-SHELL
        cd provision && DOCKER_USER=#{$USER} ./setup_privileged.sh
      SHELL

      machine.vm.provision "shell", privileged: false, inline: <<-SHELL
        cd provision && ./setup_unprivileged.sh
      SHELL
  end

  config.vm.define "secondary"  do |machine|
      machine.vm.box = $BOX
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.network "forwarded_port", guest: 3000, host: 3333

      # Local development provider
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "m3-dev-k8s"

        # Assign half CPU cores
        vb.cpus = Etc.nprocessors / 2

        # Assign 3072mb RAM (has been known to start paging using only 2gb RAM)
        vb.memory = 3072
      end

      machine.vm.provider :google do |google, override|
        # Normal benchmarks:
        google.machine_type = "n1-standard-16"
        google.preemptible = false

        # For heavy benchmarks, use pre-emptible n1-standard-64:
        # google.machine_type = "n1-standard-64"
        # google.preemptible = true
        # google.auto_restart = false
        # google.on_host_maintenance = "TERMINATE"

        google.google_project_id = $GOOGLE_PROJECT_ID
        google.google_json_key_location = $GOOGLE_JSON_KEY_LOCATION

        google.name = "m3-dev-secondary-" + $USER
        google.image_family = "ubuntu-1604-lts"
        google.zone = "us-central1-f"
        google.metadata = {}
        google.tags = ['vagrantbox', 'dev', 'network-m3coordinator']
        google.disk_size = '50' # 50gb
        google.disk_type = 'pd-ssd'
        google.autodelete_disk = true

        override.ssh.username = $USER
        override.ssh.private_key_path = $SSH_KEY
      end

      machine.vm.provision "file", source: "../provision", destination: "$HOME/provision"
      machine.vm.provision "file", source: "../../../kube", destination: "$HOME/provision/kube"

      machine.vm.provision "shell", privileged: true, inline: <<-SHELL
        cd provision && DOCKER_USER=#{$USER} ./setup_privileged.sh
      SHELL

      machine.vm.provision "shell", privileged: false, inline: <<-SHELL
        cd provision && ./setup_unprivileged.sh
      SHELL
  end

  config.vm.define "benchmarker" do |machine|
      machine.vm.box = $BOX
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.network "forwarded_port", guest: 3000, host: 3333

      # Local development provider
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "m3-dev-k8s"

        # Assign half CPU cores
        vb.cpus = Etc.nprocessors / 2

        # Assign 3072mb RAM (has been known to start paging using only 2gb RAM)
        vb.memory = 3072
      end

      machine.vm.provider :google do |google, override|
        # This machine is used for running the benchmarker:
        google.machine_type = "n1-standard-2"
        google.preemptible = false

        google.google_project_id = $GOOGLE_PROJECT_ID
        google.google_json_key_location = $GOOGLE_JSON_KEY_LOCATION

        google.name = "m3-dev-benchmarker-" + $USER
        google.image_family = "ubuntu-1604-lts"
        google.zone = "us-central1-f"
        google.metadata = {}
        google.tags = ['vagrantbox', 'dev']
        google.disk_size = '50' # 50gb
        google.disk_type = 'pd-ssd'
        google.autodelete_disk = true

        override.ssh.username = $USER
        override.ssh.private_key_path = $SSH_KEY
      end

      machine.vm.provision "file", source: "../provision", destination: "$HOME/provision"
      machine.vm.provision "file", source: "../../../kube", destination: "$HOME/provision/kube"

      machine.vm.provision "shell", privileged: true, inline: <<-SHELL
        cd provision && DOCKER_USER=#{$USER} ./setup_privileged.sh
      SHELL

      machine.vm.provision "shell", privileged: false, inline: <<-SHELL
        cd provision && ./setup_unprivileged.sh
      SHELL
  end

end
