#!/bin/bash

set -eo pipefail

echo "amainsd debug"
whoami
ls -al vendor
echo "end amainsd debug"

echo "--- :git: cleaning checkout"
if [[ -d "./_tools" ]]; then
  chmod -R +w ./_tools
fi
git clean -dffx
