# Change the default theme to be use when building the site with Hugo
[module]
  [[module.imports]]
    path = "../../../victor"

  [params.api]
    localCordinator = "http://localhost:7201/"
    apiEndpoint = "api/v1/"

# [[params.versions]]
#   version = "1.0"
#   url = "https://master.kubeflow.org"
#   [[params.versions]]
#   version = "0.9"
#   url = "https://master.kubeflow.org"
# version_menu = "Versions"