language: go
go:
  - 1.7
install: make install-ci
env:
 # Set higher timeouts for Travis
 - TEST_TIMEOUT_SCALE=20 PACKAGE=github.com/m3db/m3metrics
sudo: required
dist: trusty
script:
 - make lint
 - make test-ci-unit
