clusters:
  - namespaces:
      - namespace: aggregated
        type: aggregated
        retention: 10h
        resolution: 5s
      - namespace: default
        type: unaggregated
        retention: 48h
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - dbnode01:2379

carbon:
  ingester:
    listenAddress: "0.0.0.0:7204"
    rules:
      - pattern: .*min.aggregate.*
        aggregation:
          type: min
        policies:
          - resolution: 5s
            retention: 10h
      - pattern: .*already-aggregated.*
        aggregation:
          enabled: false
        policies:
          - resolution: 5s
            retention: 10h
      - pattern: .*
        policies:
          - resolution: 5s
            retention: 10h
