listenAddress:
  value: "0.0.0.0:7201"

logging:
  level: info

metrics:
  scope:
    prefix: "coordinator"
  prometheus:
    handlerPath: /metrics
    listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
  sanitization: prometheus
  samplingRate: 1.0
  extended: none

clusters:
  - namespaces:
      - namespace: aggregated
        type: aggregated
        retention: 10h
        resolution: 5s
      - namespace: default
        type: unaggregated
        retention: 48h
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - dbnode01:2379
      writeConsistencyLevel: majority
      readConsistencyLevel: unstrict_majority

carbon:
  ingester:
    listenAddress: "0.0.0.0:7204"
    rules:
      - pattern: .*min.aggregate.*
        aggregation:
          type: min
        policies:
          - resolution: 5s
            retention: 10h
      - pattern: .*already-aggregated.*
        aggregation:
          enabled: false
        policies:
          - resolution: 5s
            retention: 10h
      - pattern: .*
        policies:
          - resolution: 5s
            retention: 10h

tagOptions:
  idScheme: quoted
