coordinator: {}

db:
  proto:
    enabled: true
    schema_registry:
      # Need an entry for each configured namespace.
        "default":
          schemaFilePath: "/etc/m3dbnode/default_schema.proto"
          messageName: "VehicleLocation"
