coordinator:
  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

db:
  hostID:
    resolver: config
    value: m3db_local

  discovery:
    type: m3db_single_node

  proto:
    enabled: true
    schema_registry:
      # Need an entry for each configured namespace.
        "default":
          schemaFilePath: "/etc/m3dbnode/default_schema.proto"
          messageName: "VehicleLocation"
