coordinator:
  local:
    namespaces:
      - namespace: default
        type: unaggregated
        retention: 48h

db:
  hostID:
    resolver: config
    value: m3db_local

  config:
      service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
              - zone: embedded
                endpoints:
                    - 127.0.0.1:2379
      seedNodes:
          initialCluster:
              - hostID: m3db_local
                endpoint: http://127.0.0.1:2380

  # un-comment the lines below to enable Jaeger tracing. See https://www.jaegertracing.io/docs/1.9/getting-started/
  # for quick local setup (which this config will send data to).

  # tracing:
  #  backend: jaeger
