{
 "title": "Prom Remote Storage Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage (Rolled Up)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total_rolled_up[2m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Cardinality of Container CPU Usage (Rolled Up)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total_rolled_up[2m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Unaggregated)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Cardinality of Container CPU Usage (Unaggregated)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total[2m]))",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}