apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: promremotebench
  labels:
    app: promremotebench
spec:
  serviceName: "promremotebench"
  replicas: 0
  selector:
    matchLabels:
      app: promremotebench
  template:
    metadata:
      labels:
        app: promremotebench
    spec:
      containers:
      - name: promremotebench
        image: quay.io/m3db/promremotebench:latest
        env:
        - name: PROMREMOTEBENCH_TARGET
          value: "http://m3coordinator-dedicated-test-cluster:7201/api/v1/prom/remote/write"
        - name: PROMREMOTEBENCH_NUM_HOSTS
          value: "1000"
        - name: PROMREMOTEBENCH_INTERVAL
          value: "10"
        - name: PROMREMOTEBENCH_BATCH
          value: "128"
        - name: PROMREMOTEBENCH_LABELS_JSON_ENV
          value: "{\"generator\":\"PROMREMOTEBENCH_POD_NAME\"}"
        - name: PROMREMOTEBENCH_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
