version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
      - "2379-2380"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
      - "0.0.0.0:2379-2380:2379-2380"
    networks:
      - backend
    build:
      context: ../../../
      dockerfile: ./docker/m3dbnode/Dockerfile
    image: m3dbnode01:latest
  dbnode02:
    expose:
      - "9005-9009"
      - "2381-2382"
    ports:
      - "0.0.0.0:9005-9009:9005-9009"
      - "0.0.0.0:2381-2382:2381-2382"
    networks:
      - backend
    build:
      context: ../../../
      dockerfile: ./docker/m3dbnode/Dockerfile2
    image: m3dbnode02:latest
  dbnode03:
    expose:
      - "9010-9014"
      - "2383-2384"
    ports:
      - "0.0.0.0:9010-9014:9010-9014"
      - "0.0.0.0:2383-2384:2383-2384"
    networks:
      - backend
    build:
      context: ../../../
      dockerfile: ./docker/m3dbnode/Dockerfile3
    image: m3dbnode03:latest
  coordinator01:
    expose:
      - "7201"
      - "7203"
      - "7208"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7208:7208"
    networks:
      - backend
    build:
      context: ../../../
      dockerfile: ./docker/m3coordinator/Dockerfile
    image: m3coordinator01:latest
    volumes:
      - "./:/etc/m3coordinator/"
  prometheus01:
    expose:
      - "9090"
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./:/etc/prometheus/"
  grafana2:
    build:
      context: ../../../
      dockerfile: ./docker/grafana/Dockerfile
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - backend
    image: grafana/grafana:latest
networks:
  backend:
