{
 "title": "M3: Aggregator End-to-End Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(up,m3_cluster)" },
   {
    "name": "backend",
    "query": "{m3_cluster=~\"$cluster\",__name__=~\"m3aggregator_aggregator_flush_handler.*\"}"
   },
   {
    "name": "poolType",
    "query": "entry_pool,counter_elem_pool,timer_elem_pool,gauge_elem_pool,buffered_encoder_pool,sample_pool,floats_pool,stream_pool,large_floats_pool,unaggregated_iterator_pool,aggregation_types_pool,quantile_pool,bytes_pool"
   },
   {
    "name": "poolMetricType",
    "query": "total,free,get_on_empty,put_on_full"
   },
   {
    "name": "m3msg_consumer_service",
    "query": "m3aggregator_aggregator_flush_handler_placement_update{m3_cluster=~\"$cluster\",backend=\"m3msg\"}"
   },
   {
    "name": "m3msg_consumer_env",
    "query": "m3aggregator_aggregator_flush_handler_placement_update{m3_cluster=~\"$cluster\",backend=\"m3msg\"}"
   },
   { "name": "step", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Send to Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write Timed/Forwarded Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_downsampler_remote_aggregator_client_writeForwarded_success[$step]))"
    }
   ]
  },
  {
   "title": "Write Timed/Forwarded Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_downsampler_remote_aggregator_client_writeForwarded_errors[$step]))"
    }
   ]
  },
  {
   "title": "Write Queue Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_downsampler_remote_aggregator_client_writer_manager_writer_queue_successes[$step]))"
    }
   ]
  },
  {
   "title": "Write Queue Dropped/Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_downsampler_remote_aggregator_client_writer_manager_writer_queue_dropped[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_downsampler_remote_aggregator_client_writer_manager_writer_queue_errors[$step]))"
    }
   ]
  },
  { "title": "Arriving at Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Writes Success / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_addUntimed_success{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "add untimed success"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addForwarded_success{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "add forwarded success"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addTimed_success{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "add timed success"
    }
   ]
  },
  {
   "title": "Write Errors / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_addUntimed_errors{m3_cluster=~\"$cluster\"}[$step])) by (reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addForwarded_errors{m3_cluster=~\"$cluster\"}[$step])) by (reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_unknown_message_type_errors{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "unknown message type errors"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_unknown_error_type_errors{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "unknown error type errors"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_decode_errors{m3_cluster=~\"$cluster\"}[$step]))",
     "legendFormat": "server decode errors"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addTimed_errors{m3_cluster=~\"$cluster\"}[$step])) by (reason)",
     "legendFormat": "add timed error {{reason}}"
    }
   ]
  },
  {
   "title": "Metrics Dropped (All Consumers)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_flush_handler_drop_oldest_async{m3_cluster=~\"$cluster\"}[$step])",
     "legendFormat": "dropped {{reason}}"
    }
   ]
  },
  { "title": "Leaving Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Messages Buffered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(m3aggregator_aggregator_flush_handler_message_buffered{m3_cluster=~\"$cluster\",backend=\"m3msg\",component=\"producer\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "m3aggregator_aggregator_flush_handler_buffer_message_dropped{m3_cluster=~\"$cluster\",backend=\"m3msg\", component=\"producer\"}",
     "legendFormat": "{{instance}} {{__name__}}"
    }
   ]
  },
  {
   "title": "Drop types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "m3aggregator_aggregator_flush_handler_drop_oldest_async{m3_cluster=~\"$cluster\",backend=\"m3msg\",component=\"producer\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "m3aggregator_aggregator_flush_handler_drop_oldest_sync{m3_cluster=~\"$cluster\",backend=\"m3msg\",component=\"producer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Bytes buffered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(m3aggregator_aggregator_flush_handler_byte_buffered{m3_cluster=~\"$cluster\",backend=\"m3msg\", component=\"producer\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "m3aggregator_aggregator_flush_handler_buffer_byte_dropped{m3_cluster=~\"$cluster\",backend=\"m3msg\",component=\"producer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Arriving at Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Coordinator M3Msg Ingest Ack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_ack_sent{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  },
  {
   "title": "Coordinator M3Msg Ingest Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_errors{m3_cluster=~\"$cluster\"}[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_ack_encode_error{m3_cluster=~\"$cluster\"}[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_ack_write_error{m3_cluster=~\"$cluster\"}[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_errors_final{m3_cluster=~\"$cluster\"}[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_message_decode_error{m3_cluster=~\"$cluster\"}[$step]))"
    },
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_message_read_error{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  },
  {
   "title": "Coordinator M3Msg Ingest Accepted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_metric_accepted{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  },
  {
   "title": "Coordinator M3Msg Ingest Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_m3msg_metric_dropped{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  },
  {
   "title": "Coordinator M3Msg Ingest Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_success{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  },
  {
   "title": "Coordinator M3Msg Ingest Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_ingest_error{m3_cluster=~\"$cluster\"}[$step]))"
    }
   ]
  }
 ]
}