{
 "title": "M3: Aggregator Details",
 "tags": [ "disable-sync" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend",
    "query": "{__name__=~\"m3aggregator_aggregator_flush_handler.*\"}"
   },
   {
    "name": "poolType",
    "query": "entry_pool,counter_elem_pool,timer_elem_pool,gauge_elem_pool,buffered_encoder_pool,sample_pool,floats_pool,stream_pool,large_floats_pool,unaggregated_iterator_pool,aggregation_types_pool,quantile_pool,bytes_pool"
   },
   {
    "name": "poolMetricType",
    "query": "total,free,get_on_empty,put_on_full"
   },
   {
    "name": "m3msg_consumer_service",
    "query": "m3aggregator_aggregator_flush_handler_placement_update{backend=\"m3msg\"}"
   },
   {
    "name": "m3msg_consumer_env",
    "query": "m3aggregator_aggregator_flush_handler_placement_update{backend=\"m3msg\"}"
   },
   { "name": "step", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Side Write Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_addUntimed_success_latency_bucket{}) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Writes Success / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_addUntimed_success{}[$step]))",
     "legendFormat": "add untimed success"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addForwarded_success{}[$step]))",
     "legendFormat": "add forwarded success"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addTimed_success{}[$step]))",
     "legendFormat": "add timed success"
    }
   ]
  },
  {
   "title": "Write Errors / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_addUntimed_errors{}[$step])) by (reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addForwarded_errors{}[$step])) by (reason)",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_unknown_message_type_errors{}[$step]))",
     "legendFormat": "unknown message type errors"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_unknown_error_type_errors{}[$step]))",
     "legendFormat": "unknown error type errors"
    },
    {
     "expr": "sum(rate(m3aggregator_rawtcp_server_decode_errors{}[$step]))",
     "legendFormat": "server decode errors"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_addTimed_errors{}[$step])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Total Metrics / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_counters{}[$step]))",
     "legendFormat": "counters"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_timers{}[$step]))",
     "legendFormat": "timers"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_timer_batches{}[$step]))",
     "legendFormat": "timer batches"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_gauges{}[$step]))",
     "legendFormat": "gauges"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_forwarded{}[$step]))",
     "legendFormat": "forwarder"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_timed{}[$step]))",
     "legendFormat": "timed"
    }
   ]
  },
  {
   "title": "10s Flush Duration p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_manager_bucket_duration_bucket{}) by (instance, le, bucket_type, interval))"
    }
   ]
  },
  {
   "title": "Metadata Changes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_map_new_entries{}[$step])) by (instance)",
     "legendFormat": "{{instance}} map new entries"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_entry_metadata_updates{entry_type=\"untimed\"}[$step]))",
     "legendFormat": "untimed metadata updates"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_entry_metadata_updates{entry_type=\"forwarded\"}[$step]))",
     "legendFormat": "forwarded metadata updates"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_entry_metadata_updates{entry_type=\"timed\"}[$step]))",
     "legendFormat": "timed metadata updates"
    }
   ]
  },
  {
   "title": "Metrics Flushed / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_write_success{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step]))",
     "legendFormat": "flush-success"
    }
   ]
  },
  {
   "title": "Metrics Dropped (All Consumers)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_flush_handler_drop_oldest_async{}[$step])",
     "legendFormat": "dropped {{reason}}"
    }
   ]
  },
  {
   "title": "Timers dropped / s per host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_addUntimed_errors{}[$step])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "M3msg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Write Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(50, sum(rate(m3aggregator_aggregator_flush_handler_write_success{backend=\"m3msg\",component=\"producer\",consumer_service_name=\"m3coordinator\",consumer_service_env=\"production_m3_cluster_short\"}[$step])) by(instance, consumer_service_name, consumer_service_env))",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Message acked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(50, sum(rate(m3aggregator_aggregator_flush_handler_message_acked{backend=\"m3msg\",component=\"producer\",consumer_service_name=\"m3coordinator\",consumer_service_env=\"production_m3_cluster_short\"}[$step])) by(instance, consumer_service_name, consumer_service_env))\n",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Message Consume Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_handler_message_consume_latency_bucket{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}) by (instance, le, consumer_service_name))"
    }
   ]
  },
  {
   "title": "Message Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_message_dropped{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance, consumer_service_name, consumer_service_env, reason)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}} {{reason}}"
    }
   ]
  },
  { "title": "M3msg secondary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Message queue scan latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_handler_scan_total_latency_bucket{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}) by (instance, le, consumer_service_name))"
    }
   ]
  },
  {
   "title": "Message Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(50, sum(m3aggregator_aggregator_flush_handler_queue_size{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}) by (instance, consumer_service_name,consumer_service_env))",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Message Retry",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_message_retry{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (consumer_service_name,consumer_service_env)",
     "legendFormat": "{{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Placement Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_placement_update{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    },
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_placement_error{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Consumer Write Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(50,sum(rate(m3aggregator_aggregator_flush_handler_encode_error{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env))",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    },
    {
     "expr": "topk(50,sum(rate(m3aggregator_aggregator_flush_handler_decode_error{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env))",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    },
    {
     "expr": "topk(50,sum(rate(m3aggregator_aggregator_flush_handler_write_invalid_conn{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env))",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Connection Reset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(m3aggregator_aggregator_flush_handler_reset_success{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}) by (instance,consumer_service_name,consumer_service_env)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    },
    {
     "expr": "sum(m3aggregator_aggregator_flush_handler_reset_error{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}) by (instance,consumer_service_name,consumer_service_env)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "Message Write Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_write_error{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env,error_type)",
     "legendFormat": "{{instance}} {{consumer_service_name}} {{consumer_service_env}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Message Closed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(m3aggregator_aggregator_flush_handler_message_closed{backend=\"m3msg\",component=\"producer\",consumer_service_name=~\"$m3msg_consumer_service\",consumer_service_env=~\"$m3msg_consumer_env\"}[$step])) by (instance,consumer_service_name,consumer_service_env)",
     "legendFormat": "{{instance}} {{ consumer_service_name}} {{consumer_service_env}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Fd / Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Avg",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\".*node-exporter.*\"}"
      },
      {
       "expr": "avg(node_load1{instance=~\".*node-exporter.*\"})"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total[$step])) by (instance) / max(machine_cpu_cores) by (instance) * 100"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes) by (instance)-sum(node_memory_MemAvailable_bytes) by (instance))/sum(node_memory_MemAvailable_bytes) by (instance)*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Num File Descriptors / Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(process_num_fds) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Network Incoming Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device=\"eth0\"}[$step]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Network Outgoing Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{device=\"eth0\"}[$step]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaders / Followers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(m3aggregator_aggregator_election_manager_election_state==3)",
       "legendFormat": "leaders"
      },
      {
       "expr": "count(m3aggregator_aggregator_election_manager_election_state==1)",
       "legendFormat": "followers"
      }
     ]
    },
    {
     "title": "Election State",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_election_manager_election_state",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Verify Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_election_manager_verify_(leader_errors|leader_not_changed|pending_change_stale|campaign_disabled)\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "Resign Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_election_manager_resign_(timeout|errors|follower_resign)\"}",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    },
    {
     "title": "Current Resign On Close",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_election_manager_resign_on_close",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Resign On Close Success / Error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_election_manager_resign_(on_close_success|on_close_errors)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Campaign",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Campaigning",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_election_manager_campaigning",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Campaign State",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_election_manager_campaign_state",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Campaign Check",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_election_manager_campaign_check_.*\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Campaign Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_election_manager_campaign_(create_errors|errors|unknown-state)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard State",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_shards_(owned|pending_close)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Shard Changes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_shards_(add|close)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Placement Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_placement_.*\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Placement Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_placement_manager_.*\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Shard Set ID Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_shard_set_id_open",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Shard Set ID Changes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_shard_set_id_(same|changed)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    }
   ]
  },
  { "title": "Flushing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Flush Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_list_flush_duration_bucket{}) by (instance, le))"
    }
   ]
  },
  {
   "title": "Total Duration p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_manager_bucket_duration_bucket{}) by (instance, le, interval))",
     "legendFormat": "{{instance}} {{interval}}"
    }
   ]
  },
  {
   "title": "Metric Consumed / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_metric_consume_success{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{flush_type}} list flush metric consume success"
    },
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_metric_consume_errors{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{flush_type}} list flush metric consume errors"
    }
   ]
  },
  {
   "title": "Metric Discarded / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_discarded{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{flush_type}} {{resolution}} discarded"
    },
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_metric_discarded{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{flush_type}} {{resolution}} metric discarded"
    }
   ]
  },
  {
   "title": "On Forwarded Metrics Consumed / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"m3aggregator_aggregator_list_flush_on_consumed_.*\",flush_type=\"forwarded\"}",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}} {{__name__}}"
    }
   ]
  },
  {
   "title": "On Forwarded Metrics Discarded / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_on_discarded{flush_type=\"forwarded\"}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}} {{__name__}}"
    }
   ]
  },
  {
   "title": "Writer Flushes / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_writer_flush_success{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}} success"
    },
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_writer_flush_errors{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}} errors"
    }
   ]
  },
  {
   "title": "Elems Collected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"m3aggregator_aggregator_list_flush_(collected|elem_collected)\"}",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}}"
    }
   ]
  },
  {
   "title": "Stale Flushes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(m3aggregator_aggregator_list_flush_before_stale{}[$step])",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}}"
    }
   ]
  },
  {
   "title": "FlushBefore Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_list_flush_before_duration_bucket{}) by (instance, le, list_type, resolution))",
     "legendFormat": "{{instance}} {{list_type}} {{resolution}}"
    }
   ]
  },
  {
   "title": "Flush Times Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "m3aggregator_aggregator_flush_times_manager_flush_times_unmarshal_errors",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flushing (Leader)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flush Queue Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_manager_leader_queue_size",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flusher Update Flush Times / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_flush_manager_leader_update_flush_times{}[$step])",
       "legendFormat": "{{instance}} {{flusher_type}}"
      }
     ]
    },
    {
     "title": "Flush Times Persistence",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_flush_times_manager_flush_times_persist_(success|errors)\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Flush Times Persistence Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_times_manager_flush_times_persist_success_latency_bucket{}) by (instance, le))",
       "legendFormat": "{{instance}} success"
      },
      {
       "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_times_manager_flush_times_persist_error_latency_bucket{}) by (instance, le))",
       "legendFormat": "{{instance}} error"
      }
     ]
    },
    {
     "title": "Flush Task Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_placement_manager_.*\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Flush Calls Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_flush_before_cutover{}[$step])",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}} before cutover"
      },
      {
       "expr": "rate(m3aggregator_aggregator_list_flush_between_cutover_cutoff{}[$step])",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}}  between cutover cutoff"
      },
      {
       "expr": "rate(m3aggregator_aggregator_list_flush_between_cutoff_bufferend{}[$step])",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}} between cutoff bufferend"
      },
      {
       "expr": "rate(m3aggregator_aggregator_list_flush_after_bufferend{}[$step])",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}} after bufferend"
      },
      {
       "expr": "m3aggregator_aggregator_list_flush_discard",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flushing (Follower)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flushes / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_flush_manager_follower_kv_update_flush{}[$step])",
       "legendFormat": "{{instance}} update flush"
      },
      {
       "expr": "rate(m3aggregator_aggregator_flush_manager_follower_forced_flush{}[$step])",
       "legendFormat": "{{instance}} forced flush"
      }
     ]
    },
    {
     "title": "DiscardBefore / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_discard_before{}[$step])",
       "legendFormat": "{{instance}} {{list_type}} {{resolution}}"
      }
     ]
    },
    {
     "title": "Flusher KV Updates / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_flush_manager_follower_kv_updates{}[$step])",
       "legendFormat": "{{instance}} {{flusher_type}}"
      }
     ]
    },
    {
     "title": "Can't Lead Reasons",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_manager_follower_not_campaigning",
       "legendFormat": "{{instance}} {{__name__}}"
      },
      {
       "expr": "m3aggregator_aggregator_flush_manager_follower_flush_windows_not_ended",
       "legendFormat": "{{instance}} {{flusher_type}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Flush Times Watch Creation Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_manager_follower_watch_create_errors",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flush Times Errors For Standard Metrics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_flush_manager_follower_(shard_not_found|resolution_not_found)\",flusher_type=\"standard\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Flush Times Errors For Forwarded Metrics",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_flush_manager_follower_(shard_not_found|resolution_not_found|nil_forwarded_times|num_forwarded_times_not_found)\",flusher_type=\"forwarded\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Forwarded Metrics Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Register Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_success{writer_type=\"forwarded\",action=\"register\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    },
    {
     "title": "Register Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_errors{writer_type=\"forwarded\",action=\"register\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} {{reason}}"
      }
     ]
    },
    {
     "title": "Unregister Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_success{writer_type=\"forwarded\",action=\"unregister\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} {{reason}}"
      }
     ]
    },
    {
     "title": "Unregister Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_errors{writer_type=\"forwarded\",action=\"unregister\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} {{reason}}"
      }
     ]
    },
    {
     "title": "Prepare / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_prepare{writer_type=\"forwarded\",action=\"prepare\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} {{reason}}"
      }
     ]
    },
    {
     "title": "Flush Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_success{writer_type=\"forwarded\",action=\"flush\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} {{reason}}"
      }
     ]
    },
    {
     "title": "Flush Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_errors{writer_type=\"forwarded\",action=\"flush\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    },
    {
     "title": "Aggregations Added / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_added{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    },
    {
     "title": "Aggregations Removed / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_removed{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    },
    {
     "title": "On Done Write Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_on_done_not_write{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} not write"
      },
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_on_done_write_success{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}} write success"
      }
     ]
    },
    {
     "title": "On Done Write Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_on_done_write_errors{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    },
    {
     "title": "On Done Unexpected RefCount / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_list_writer_aggregations_on_done_unexpected_refcnt{writer_type=\"forwarded\"}[$step])",
       "legendFormat": "{{instance}} {{resolution}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writes Latency (p99)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_client_writeForwarded_success_latency{quantile=\"0.99\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Writes Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writeforwarded_success)",
       "legendFormat": "client write forwarded success"
      }
     ]
    },
    {
     "title": "Writes Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"m3aggregator_aggregator_client_writeUntimed.*_errors\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "sum(m3aggregator_aggregator_client_writeForwarded_errors)",
       "legendFormat": "client write forwarded errors"
      },
      {
       "expr": "sum(m3aggregator_aggregator_client_flush_errors)",
       "legendFormat": "client flush errors"
      },
      {
       "expr": "sum(m3aggregator_aggregator_client_shard_not_writeable)",
       "legendFormat": "client shart not writeable"
      },
      {
       "expr": "sum(m3aggregator_aggregator_client_shard_not_owned)",
       "legendFormat": "client shard not owned"
      }
     ]
    },
    {
     "title": "Aggregator Instances Added / Removed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_instances) by (instance, __name__, action)",
       "legendFormat": "{{instance}} {{__name__}} {{action}}"
      }
     ]
    },
    {
     "title": "Buffer Enqueued / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_buffers{action=\"enqueued\"}) by (instance,__name__)",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Buffer Write Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_buffers{action=~\".*_error\"}) by (instance, __name__, action)",
       "legendFormat": "{{instance}} {{name}} {{action}}"
      }
     ]
    },
    {
     "title": "Write Queue Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_client_writer_manager_writer_queue_queue_length_sum",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Queue Enqueue Success / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_successes{action=\"enqueue\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Queue Enqueue Dropped / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_dropped{action=\"enqueue\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Queue Enqueue Error / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_errors) by (instance,error_type)",
       "legendFormat": "{{instance}} {{error_type}}"
      }
     ]
    },
    {
     "title": "Write Queue Connection Write Successes / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_successes{action=\"conn_write\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Queue Connection Write Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_errors{action=\"conn_write\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Write Retries / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_connection_retries{action=\"write\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Write Error Reasons / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_client_writer_manager_writer_queue_connection_errors) by (instance, error_type)",
       "legendFormat": "{{instance}} {{error_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate Limiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Value Rate Limiting / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_entry_value_rate_limit_exceeded{}[$step])",
       "legendFormat": "{{instance}} {{entry_type}}"
      }
     ]
    },
    {
     "title": "Dropped Values / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_entry_dropped_values{}[$step])",
       "legendFormat": "{{instance}} {{entry_type}}"
      }
     ]
    },
    {
     "title": "Write New Metric Rate Limiting / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_map_new_metric_rate_limit_exceeded{}[$step])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "New Metric Warmup Period",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_map_no_rate_limit_warmup",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Dropped New Metrics / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(m3aggregator_aggregator_map_dropped_new_metrics{}[$step])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "Untimed Metrics Metadata Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"m3aggregator_aggregator_entry_(empty_metadatas|no_applicable_metadata|no_pipelines_in_metadata|empty_pipeline|no_aggregation_in_pipeline|stale_metadata|tombstoned_metadata)\", entry_type=\"untimed\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Forwarded Metrics Metadata Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"m3aggregator_aggregator_entry_(arrived_too_late|duplicate_sources)\",entry_type=\"forwarded\"}) by (__name__)",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Encoded Metric / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3aggregator_aggregator_list_writer_encode_success{}[$step])) by (instance, resolution)",
       "legendFormat": "{{instance}} encode success {{resolution}}"
      },
      {
       "expr": "sum(rate(m3aggregator_aggregator_list_writer_encode_errors{}[$step])) by (instance, resolution)",
       "legendFormat": "{{instance}} encode errors {{resolution}}"
      }
     ]
    },
    {
     "title": "Routed Buffer / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3aggregator_aggregator_list_writer_route_success{}[$step])) by (instance, resolution)",
       "legendFormat": "{{instance}} success {{resolution}}"
      },
      {
       "expr": "sum(rate(m3aggregator_aggregator_list_writer_route_errors{}[$step])) by (instance, resolution)",
       "legendFormat": "{{instance}} errors {{resolution}}"
      }
     ]
    },
    {
     "title": "Enqueue / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"m3aggregator_aggregator_flush_handler_[[backend]]_queue_(enqueue_errors|enqueue_successes)\"}) by (instance, __name__)",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_flush_handler_queue_size{backend=~\"$backend\"}) by (instance, backend)",
       "legendFormat": "{{instance}} {{backend}}"
      }
     ]
    },
    {
     "title": "Buffered Writes / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3aggregator_aggregator_flush_handler_write_success{backend=~\"$backend\"}[$step])) by (instance, backend)",
       "legendFormat": "{{instance}} {{backend}}"
      }
     ]
    },
    {
     "title": "Buffer Write Errors / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3aggregator_aggregator_flush_handler_write_error{backend=~\"$backend\"}[$step])) by (instance, backend)",
       "legendFormat": "{{instance}} {{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ticking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tick Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_tick_duration_bucket{}) by (instance, le))",
       "legendFormat": "{{instance}} p99"
      }
     ]
    },
    {
     "title": "Active Entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_tick_active_entries",
       "legendFormat": "{{instance}} {{metric_type}}"
      }
     ]
    },
    {
     "title": "Expired Entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_tick_expired_entries",
       "legendFormat": "{{instance}} {{metric_type}}"
      }
     ]
    },
    {
     "title": "Active Elems By Resolution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_tick_active_elem",
       "legendFormat": "{{instance}} {{metric_type}} {{resolution}}"
      }
     ]
    },
    {
     "title": "Shard Check",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_tick_shard_check_.*\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Flush Times Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_tick_flush_times_errors",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_runtime_memory_num_gc) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Pause Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(m3aggregator_runtime_memory_gc_pause_ms{quantile=\"0.99\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Num Go Routines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_runtime_num_goroutines",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pooling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total / Free / Put-On-Full",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_[[poolType]]_[[poolMetricType]]\"}",
       "legendFormat": "{{instance}} {{__name__}} {{bucket_capacity}}"
      },
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_stream_[[poolType]]_[[poolMetricType]]\"}",
       "legendFormat": "{{instance}} {{__name__}} {{bucket_capacity}}"
      },
      {
       "expr": "{__name__=~\"m3aggregator_aggregator_flush_handler_[[poolType]]_[[poolMetricType]]\"}",
       "legendFormat": "{{instance}} {{__name__}} {{bucket_capacity}}"
      },
      {
       "expr": "{__name__=~\"m3aggregator_rawtcp_server_[[poolType]]_[[poolMetricType]]\"}",
       "legendFormat": "{{instance}} {{__name__}} {{bucket_capacity}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Instance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per-Instance Metrics / s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum({__name__=~\"m3aggregator_aggregator_(counters|timers|timer_batches|gauges)\"}) by (__name__, host, instance)",
       "legendFormat": "{{__name__}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "M3msg buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Messages Buffered",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_flush_handler_message_buffered{backend=\"m3msg\",component=\"producer\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Bytes buffered",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(m3aggregator_aggregator_flush_handler_byte_buffered{backend=\"m3msg\", component=\"producer\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Message Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_handler_buffer_message_dropped{backend=\"m3msg\", component=\"producer\"}",
       "legendFormat": "{{instance}} {{__name__}}"
      }
     ]
    },
    {
     "title": "Bytes Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 70 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_handler_buffer_byte_dropped{backend=\"m3msg\",component=\"producer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Topic Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_handler_topic_update_success{backend=\"m3msg\",component=\"producer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Buffer Scan Batch P99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 77 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(m3aggregator_aggregator_flush_handler_buffer_scan_batch_bucket{backend=\"m3msg\",component=\"producer\"}) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Drop types",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3aggregator_aggregator_flush_handler_drop_oldest_async{backend=\"m3msg\",component=\"producer\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "m3aggregator_aggregator_flush_handler_drop_oldest_sync{backend=\"m3msg\",component=\"producer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}