{
 "title": "M3Coordinator Details",
 "tags": [ "disable-sync" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries Per Second (remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coordinator_fetch_success{source=\"remote\"}[1m])",
     "legendFormat": "queries_per_second"
    }
   ]
  },
  {
   "title": "Query Errors Per Second (remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_fetch_errors{source=\"remote\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Writes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coordinator_write_success{source=\"remote\"}[1m])",
     "legendFormat": "write_per_second"
    }
   ]
  },
  {
   "title": "Write Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_write_errors{source=\"remote\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}