{
 "title": "M3nsch",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(agent_write_success,instance)"
   },
   { "name": "step", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Write Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write Success / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agent_write_success{instance=~\"$instance\"}[$step])) by (instance)",
     "legendFormat": "writes-success-{{instance}}"
    }
   ]
  },
  {
   "title": "Write Errors / s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agent_write_errors{instance=~\"$instance\"}[$step])) by (instance)",
     "legendFormat": "writes-errors-{{instance}}"
    }
   ]
  },
  {
   "title": "Write Success P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "agent_write_success_latency{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "write-success-{{instance}}-p99"
    }
   ]
  },
  {
   "title": "Write Errors P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "agent_write_errors_latency{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "write-errors-{{instance}}-p99"
    }
   ]
  }
 ]
}