{
 "title": "Temporal function comparison",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "avg_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "avg_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "count_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "count_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "holt_winters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "holt_winters(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range], 0.3, 0.8)",
     "legendFormat": "Prom"
    },
    {
     "expr": "holt_winters(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range], 0.3, 0.8)",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "min_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "min_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "delta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "delta(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "idelta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "idelta(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "irate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "irate(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "max_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "max_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "increase(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "sum_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "sum_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "predict_linear",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range], 1)",
     "legendFormat": "Prom"
    },
    {
     "expr": "predict_linear(scrape_duration_seconds{instance=~\"m3db_seed:9004\"}[$range], 1)",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "stddev_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stddev_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "stddev_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "rate(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "stdvar_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stdvar_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "stdvar_over_time(scrape_duration_seconds{instance=~\"m3db_seed:9004\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "resets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resets(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "resets(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "deriv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "deriv(scrape_duration_seconds{instance=~\"m3db_seed:9004\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "quantile_over_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.3, scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "quantile_over_time(0.3, scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  },
  {
   "title": "changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(scrape_duration_seconds{instance=~\"m3db_seed:9004\", role=\"remote\"}[$range])",
     "legendFormat": "Prom"
    },
    {
     "expr": "changes(scrape_duration_seconds{instance=~\"m3db_seed:9004\"}[$range])",
     "legendFormat": "M3"
    }
   ]
  }
 ]
}